- name: Cancel instances
  hosts: localhost
  gather_facts: False
  tasks:
  - name: Cancel by tag
    local_action:
      module: sl_vm
      state: absent
      tags: ['tomcat-test-mcltn','tomcat-test-mcltn-sjc']
