- name: Cancel instances
  hosts: localhost
  gather_facts: False
  tasks:
  - name: Cancel by tag
    local_action:
      module: sl
      state: absent
      tags: ['mongo-test-mcltn', 'mongo-test-mcltn-master']
