---
#- name: Mount drive
#  hosts: mongo-test-mcltn
#  remote_user: root
#  gather_facts: False
#  tasks:
#  - script: mount_disk.sh

- name: Install Mongo
  hosts: mongo-test-mcltn
  remote_user: root
  gather_facts: True
  roles:
  - role: common
  - role: replica_set

- hosts: mongo-test-mcltn-master
  remote_user: root
  tasks:
    - include: roles/replica_set/tasks/replset_init.yaml
