---
- name: apt clean
  command: sudo apt-get -y clean

- name: apt autoclean
  command: sudo apt-get -y clean

- name: Import the public key used by the package management system
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=7F0CEB10 state=present

- name: Add MongoDB repository
  apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' state=present

- name: update apt cache
  command: apt-get update

- name: install mongodb
  command: apt-get install mongodb-org
  notify:
  - start mongodb